### ISSUE TITLE
手势侧滑返回

### ISSUE THREAD

**Issue by 979881765** [SmileZXLee/ZXNavigationBar#1]
手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下

**Comment by SmileZXLee** [comment]
> 手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下

你好，是自定义导航栏和系统导航栏混合使用的时候吗

**Comment by SmileZXLee** [comment]
> 手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下

如果是纯自定义导航栏的情况下，建议在appdelegate的 `application:didFinishLaunchingWithOptions:`方法中添加`[UINavigationController zx_hideAllNavBar];`(注意要放在导航控制器初始化之前),且需要`#import "ZXNavigationBarController.h"`

**Comment by 979881765** [comment]
就是这样的 ，返回时




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZXLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 上午10:39
收件人:&nbsp;"SmileZXLee/ZXNavigationBar"<ZXNavigationBar@noreply.github.com&gt;;
抄送:&nbsp;"佐手ㄨ縴祐手"<960101847@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SmileZXLee/ZXNavigationBar] 手势侧滑返回 (#1)





  
手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下
  
如果是纯自定义导航栏的情况下，建议在appdelegate的 application:didFinishLaunchingWithOptions:方法中添加[UINavigationController zx_hideAllNavBar];(注意要放在导航控制器初始化之前),且需要#import "ZXNavigationBarController.h"

**Comment by SmileZXLee** [comment]
> 就是这样的 ，返回时
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ZXLee"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月26日(星期四) 上午10:39 收件人:&nbsp;"SmileZXLee/ZXNavigationBar"<ZXNavigationBar@noreply.github.com&gt;; 抄送:&nbsp;"佐手ㄨ縴祐手"<960101847@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [SmileZXLee/ZXNavigationBar] 手势侧滑返回 (#1) 手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下 如果是纯自定义导航栏的情况下，建议在appdelegate的 application:didFinishLaunchingWithOptions:方法中添加[UINavigationController zx_hideAllNavBar];(注意要放在导航控制器初始化之前),且需要#import "ZXNavigationBarController.h" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，方便提供一下详细的描述吗，目前只能看到【就是这样的 ，返回时】这几个字，感谢！

**Comment by 979881765** [comment]
传的视频没有吗




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            960101847
                            
                            
                                
                                    邮箱：960101847@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2020年03月26日 15:09，ZXLee 写道： 

就是这样的 ，返回时
…
------------------ 原始邮件 ------------------ 发件人: "ZXLee"<notifications@github.com>; 发送时间: 2020年3月26日(星期四) 上午10:39 收件人: "SmileZXLee/ZXNavigationBar"<ZXNavigationBar@noreply.github.com>; 抄送: "佐手ㄨ縴祐手"<960101847@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [SmileZXLee/ZXNavigationBar] 手势侧滑返回 (#1) 手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下 如果是纯自定义导航栏的情况下，建议在appdelegate的 application:didFinishLaunchingWithOptions:方法中添加[UINavigationController zx_hideAllNavBar];(注意要放在导航控制器初始化之前),且需要#import "ZXNavigationBarController.h" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，方便提供一下详细的描述吗，目前只能看到【就是这样的 ，返回时】这几个字，感谢！

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SmileZXLee/ZXNavigationBar/issues/1#issuecomment-604266855",
"url": "https://github.com/SmileZXLee/ZXNavigationBar/issues/1#issuecomment-604266855",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SmileZXLee** [comment]
> 传的视频没有吗 960101847 邮箱：960101847@qq.com Signature is customized by Netease Mail Master 在2020年03月26日 15:09，ZXLee 写道： 就是这样的 ，返回时 … ------------------ 原始邮件 ------------------ 发件人: "ZXLee"<notifications@github.com>; 发送时间: 2020年3月26日(星期四) 上午10:39 收件人: "SmileZXLee/ZXNavigationBar"<ZXNavigationBar@noreply.github.com>; 抄送: "佐手ㄨ縴祐手"<960101847@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [SmileZXLee/ZXNavigationBar] 手势侧滑返回 (#1) 手势侧滑慢慢向右滑动，等滑动到最右边的时候 会出现系统导航栏突然闪烁一下 如果是纯自定义导航栏的情况下，建议在appdelegate的 application:didFinishLaunchingWithOptions:方法中添加[UINavigationController zx_hideAllNavBar];(注意要放在导航控制器初始化之前),且需要#import "ZXNavigationBarController.h" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好，方便提供一下详细的描述吗，目前只能看到【就是这样的 ，返回时】这几个字，感谢！ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#1 (comment)](https://github.com/SmileZXLee/ZXNavigationBar/issues/1#issuecomment-604266855)", "url": "[#1 (comment)](https://github.com/SmileZXLee/ZXNavigationBar/issues/1#issuecomment-604266855)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

没有看到视频 如果您方便的话，可以直接将视频发送至我的邮箱：admin@zxlee.cn，有劳了
