### ISSUE TITLE
判断刘海屏的方式有问题,导致在 iphone 11 pro max上获取到的状态栏高度是20,进而导致标题偏上

### ISSUE THREAD

**Issue by LayDownAll** [SmileZXLee/ZXNavigationBar#11]
![image](https://user-images.githubusercontent.com/16486503/88615396-70a12d80-d0c4-11ea-92f4-73689479d31b.png)
好像是这个刘海屏的判断有问题
/**
 判断是否是刘海屏

 @return 是否是刘海屏
 */
#define ZXIsBangScreen ({\
int cFlag = 0;\
if (@available(iOS 11.0, *)) {\
if ([UIApplication sharedApplication].delegate.window.safeAreaInsets.top == 44) {\
cFlag = 1;\
}else{\
cFlag = 0;\
}\
}else{\
cFlag = 0;\
}\
cFlag;\
})
我测试的手机是iphone 11 pro max  你这个宏定义获取到的状态栏高度是20,实际高度应该是44

**Comment by SmileZXLee** [comment]
您好，您的iPhone 11 pro max的软件版本是iOS 14的吗，我使用iOS 13.5的iPhone 11 pro max未发现您描述的问题，如果方便的话可以帮我打印一下[UIApplication sharedApplication].delegate.window.safeAreaInsets.top的值吗？感谢！

**Comment by vlay1314** [comment]
我设置导航栏为透明的时候，切换到下一个页面的是系统的导航栏，会有向上偏移的。初始化是在layoutsubviews上初始化吗？我在viewdidload上初始化的。

**Comment by SmileZXLee** [comment]
> 我设置导航栏为透明的时候，切换到下一个页面的是系统的导航栏，会有向上偏移的。初始化是在layoutsubviews上初始化吗？我在viewdidload上初始化的。

你好，方便提供一个demo或者相关代码片段和截图吗，以便我定位问题和改正，感谢！

**Comment by LayDownAll** [comment]
> 您好，您的iPhone 11 pro max的软件版本是iOS 14的吗，我使用iOS 13.5的iPhone 11 pro max未发现您描述的问题，如果方便的话可以帮我打印一下[UIApplication sharedApplication].delegate.window.safeAreaInsets.top的值吗？感谢！

po [UIApplication sharedApplication].delegate.window.safeAreaInsets.top
error: <user expression 0>:1:44: property 'window' not found on object of type 'id' 可能是因为我是用了SceneDelegate,所以你这种获取高度的方式好像不行,因为这个时候AppDelegate没有window这个属性了

**Comment by SmileZXLee** [comment]
> > 您好，您的iPhone 11 pro max的软件版本是iOS 14的吗，我使用iOS 13.5的iPhone 11 pro max未发现您描述的问题，如果方便的话可以帮我打印一下[UIApplication sharedApplication].delegate.window.safeAreaInsets.top的值吗？感谢！
> 
> po [UIApplication sharedApplication].delegate.window.safeAreaInsets.top
> error: <user expression 0>:1:44: property 'window' not found on object of type 'id' 可能是因为我是用了SceneDelegate,所以你这种获取高度的方式好像不行,因为这个时候AppDelegate没有window这个属性了

感谢您的反馈与帮助，我在1.2.2版本中修复了这一问题，您可以更新一下。

**Comment by SmileZXLee** [comment]
> 我设置导航栏为透明的时候，切换到下一个页面的是系统的导航栏，会有向上偏移的。初始化是在layoutsubviews上初始化吗？我在viewdidload上初始化的。

请您在系统的导航控制器的viewDidLoad方法中作如下设置：
```objc
//注意，因导航栏默认被隐藏，请手动设置显示导航栏
self.navigationController.navigationBarHidden = NO;
 //如果希望view从导航栏下方开始，请设置导航栏为不透明
 self.navigationController.navigationBar.translucent = NO;
```
