### ISSUE TITLE
与masonry布局冲突

### ISSUE THREAD

**Issue by lovin67** [SmileZXLee/ZXNavigationBar#12]
我baseController继承ZXNavigationBarController
然后隐藏导航栏
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    self.zx_hideBaseNavBar = YES;
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    self.zx_hideBaseNavBar = NO;
} 

masonry布局为
    [self.view addSubview:self.tableView];

    [_tableView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.mas_equalTo(UIEdgeInsetsMake(kNavStatusBar, 0, kTabBarHeight, 0));
    }];

其中kNavStatusBar打印为44 但是运行结果tableView.top 为0

**Comment by SmileZXLee** [comment]
`ZXNavigationBar` 是一个属于控制器的view，因此如需隐藏自定义导航栏，只需要在`-viewDidload`中设置`self.zx_hideBaseNavBar = YES;`即可，不需要在`viewWillDisappear`中设置`self.zx_hideBaseNavBar = NO;`
您反馈的问题我这边测试未发现问题，我测试的demo您可以下载看下：http://www.zxlee.cn/temp/ZXNavigationBarTestDemo.zip 
如果您方便的话可以把遇到问题的地方抽出来做个demo给我看下，以便我检查问题，感谢！
