### ISSUE TITLE
代码建议

### ISSUE THREAD

**Issue by myDonghao** [SmileZXLee/ZXNavigationBar#13]
UIView+ZXNavFrameExtension这个分类里面的方法建议加上前缀`zx_`。

**Comment by SmileZXLee** [comment]
嗯嗯，感谢建议，若对您项目影响不大的话我下个版本一起改哦，若有影响我新开一个版本修改。

**Comment by myDonghao** [comment]
我是在审查项目中代码的时候看到的，没啥影响。
