### ISSUE TITLE
iPad竖屏下上面导航条高度为50

### ISSUE THREAD

**Issue by myDonghao** [SmileZXLee/ZXNavigationBar#14]
我去，我一直以为iPad上面也是44的高度呢，它竟然是50。。
完犊子了，那我之前的项目岂不是也要炸锅....
大佬，能不能考虑一下iPad上的适配啊，[拜托了],我先去做适配去了

**Comment by myDonghao** [comment]
不对，我先去核实一下

**Comment by myDonghao** [comment]
present的vc,系统的导航条高度为56...

**Comment by SmileZXLee** [comment]
已兼容iPad，pod还没更新，我等等到家了提交一下pod的更新

**Comment by SmileZXLee** [comment]
pod已更新至1.2.4

**Comment by myDonghao** [comment]
大佬辛苦💦，我是直接在给自定义导航条高度赋值来适配的...以前还真没留意这个问题

**Comment by SmileZXLee** [comment]
> 大佬辛苦💦，我是直接在给自定义导航条高度赋值来适配的...以前还真没留意这个问题

我也没留意到，感谢指正！
