### ISSUE TITLE
单页面无法禁用全屏手势

### ISSUE THREAD

**Issue by VictDog** [SmileZXLee/ZXNavigationBar#16]
![image](https://user-images.githubusercontent.com/13920746/93958913-2669bf00-fd8a-11ea-8b52-9c09f8f557c8.png)

**Comment by SmileZXLee** [comment]
* 若您需要在特定页面禁止全屏手势，您可以在子控制器的`-viewWillAppear`或`-viewDidAppear`中书写：
```objc
//将全屏手势范围缩小到宽度的十分之一
self.zx_popGestureCoverRatio = 0.1;
```
* 若您需要在特定页面拦截全屏手势pop事件，您可以在子控制器中书写：
```objc
//拦截侧滑返回手势和返回按钮点击事件
self.zx_handlePopBlock = ^BOOL(ZXNavigationBarController * _Nonnull viewController, ZXNavPopBlockFrom popBlockFrom) {
    //viewController:当前控制器
    //popBlockFrom:通过什么方式(点击返回按钮或侧滑返回手势)触发pop操作
    
    //doSomething
    //返回YES则代表不禁止pop操作，返回NO则禁止pop操作
    return YES;
};
```

**Comment by VictDog** [comment]
好的，谢谢。有个小建议， 如果self.view 能自动向下偏移 statusBar 和 navigationBar 的高度就好了。 开始用系统的，换了您的这个之后， self.view 的顶部不是从导航栏底部开始，而是从0开始。所以就要调整约束了。

**Comment by SmileZXLee** [comment]
> 好的，谢谢。有个小建议， 如果self.view 能自动向下偏移 statusBar 和 navigationBar 的高度就好了。 开始用系统的，换了您的这个之后， self.view 的顶部不是从导航栏底部开始，而是从0开始。所以就要调整约束了。

如果您的self.view从控制器的xib中加载，`ZXNavigationBar`会自动调整您的view距上的约束为导航栏高度，不需要手动调整约束。
若您的self.view是通过纯代码创建的，则在设置它的frame时，y值需设置为`ZXNavBarHeight`，您可以直接使用这个宏。

**Comment by VictDog** [comment]
好的，谢谢。
