### ISSUE TITLE
手势返回时有问题

### ISSUE THREAD

**Issue by H4AER** [SmileZXLee/ZXNavigationBar#17]
导航栏继承与ZXNavigationBarNavigationController
vc继承与ZXNavigationBarController

侧滑返回时有问题
视频链接
https://gitee.com/1264788359/pro/raw/master/2020-10-10%2010.47.39.mp4

**Comment by H4AER** [comment]
v1.2.4

**Comment by SmileZXLee** [comment]
> 导航栏继承与ZXNavigationBarNavigationController
> vc继承与ZXNavigationBarController
> 
> 侧滑返回时有问题
> 视频链接
> https://gitee.com/1264788359/pro/raw/master/2020-10-10%2010.47.39.mp4

您好，我无法复现这一问题，麻烦您提供一下demo或者相关设置的代码片段以便我定位问题哦，感谢！

**Comment by SmileZXLee** [comment]
若您设置了`self.zx_navEnableSmoothFromSystemNavBar = YES;`请删除这一行。

**Comment by H4AER** [comment]
感谢回复，删掉FDFullscreenPopGesture后好了

**Comment by SmileZXLee** [comment]
> 感谢回复，删掉FDFullscreenPopGesture后好了

嗯嗯，因`FDFullscreenPopGesture`默认会在`-viewWillDisappear`中显示系统导航栏，`ZXNavigationBar`会在`-viewWillAppear`中隐藏系统导航栏，所以会导致此问题，`ZXNavigationBar`提供了全屏返回手势的功能，所以可以不需要添加`FDFullscreenPopGesture`。
