### ISSUE TITLE
zx_navRightBtn 使用setAttributedTitle 时，按钮宽度无法自适应

### ISSUE THREAD

**Issue by H4AER** [SmileZXLee/ZXNavigationBar#19]
NSMutableAttributedString *att = [[NSMutableAttributedString alloc]initWithString:@"剩余时间00:45"];
    att.yy_font = [UIFont systemFontOfSize:14];
    [att yy_setColor:KRGBColor(0xFF3C3C) range:NSMakeRange(4, 5)];
    [self.zx_navRightBtn setAttributedTitle:att forState:UIControlStateNormal];

**Comment by SmileZXLee** [comment]
感谢您的反馈，我将在1-2日内修复这一问题，很抱歉影响您的使用了。

**Comment by H4AER** [comment]
好的，非常感谢

**Comment by SmileZXLee** [comment]
感谢您的反馈！！pod 1.2.5已修复此问题。

**Comment by H4AER** [comment]
pod 1.2.5 无相关更新内容
https://upload-images.jianshu.io/upload_images/1290409-c705f9a6d8bf8a6e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by SmileZXLee** [comment]
不好意思哈，请您更新到1.2.6，昨晚迷糊了，pod引用的文件忘记更新了。

**Comment by H4AER** [comment]
非常感谢
