### ISSUE TITLE
zx_popGestureCoverRatio问题

### ISSUE THREAD

**Issue by Mrkinpa** [SmileZXLee/ZXNavigationBar#20]
设置了该属性后无效、还是全局返回的手势、viewcontroller和navcontoller都继承了ZX

**Comment by SmileZXLee** [comment]
您好，zx_popGestureCoverRatio范围为0-1之间，我在控制器中设置`self.zx_popGestureCoverRatio=0.1`并测试是正常的，pop手势触发范围缩小为屏幕宽度的十分之一。若您那边还是有问题，可以提供给我一下相关设置的代码片段或demo以便我定位原因哦，感谢！
