### ISSUE TITLE
设置返回按钮默认图片

### ISSUE THREAD

**Issue by Wuou** [SmileZXLee/ZXNavigationBar#21]
将HEBaseViewController 继承ZXNavigationBarController，我再基类里定义返回按钮图片，    self.zx_backBtnImageName = @"back_black"，所有的顶层ViewController都会显示返回按钮。

设置返回按钮默认图片应该也需要加入这个判断    if(self.navigationController && self.navigationController.viewControllers.count > 1)

**Comment by Wuou** [comment]
可能其他属性的设置 也会有这个问题哦  所有提前去设置push后的属性的地方 最好检查下。。。

**Comment by SmileZXLee** [comment]
感谢您的反馈！！pod 1.2.5已修复此问题。

**Comment by Wuou** [comment]
> 感谢您的反馈！！pod 1.2.5已修复此问题。
还是有这个问题啊，
![image](https://user-images.githubusercontent.com/14285500/97140439-93acad80-1797-11eb-834d-94c4720079a5.png)


在这里加个判断？if(self.navigationController && self.navigationController.viewControllers.count > 1)
![Uploading image.png…]()

**Comment by Wuou** [comment]
- (void)setZx_backBtnImageName:(NSString *)zx_backBtnImageName{
    if(self.navigationController && self.navigationController.viewControllers.count > 1) {
        _zx_backBtnImageName = zx_backBtnImageName;
        UIImage *backImg = [self getBackBtnImage];
        [self.zx_navLeftBtn setImage:backImg forState:UIControlStateNormal];
    }
}

**Comment by SmileZXLee** [comment]
不好意思哈，请您更新到1.2.6，昨晚迷糊了，pod引用的文件忘记更新了。

**Comment by Wuou** [comment]
现在可以了
