### ISSUE TITLE
返回按钮

### ISSUE THREAD

**Issue by WangJxin1992** [SmileZXLee/ZXNavigationBar#23]
用系统的导航栏push继承ZXNavigationBar导航的页面 如何去掉系统返回的字段
![WeChat0bfcae1116e78a19c2ebd70b85cb30a0](https://user-images.githubusercontent.com/15007792/97860310-e3154f80-1d3c-11eb-917f-a5025b61b39b.png)在视图层看到的效果是这样的![WeChatee10ac1d3e869a923fce888f41ab2508](https://user-images.githubusercontent.com/15007792/97861046-1d332100-1d3e-11eb-92ee-9465963540ff.png)最上方有一个导航

**Comment by SmileZXLee** [comment]
当`ZXNavigationBar`显示时，默认会隐藏系统导航栏，若您在控制器加载后通过代码展示系统导航栏，请注释相关代码。

**Comment by WangJxin1992** [comment]
push出来的B页面没有相关代码，是其他问题导致的没有隐藏系统导航。
补充提问：模态present推一个继承ZXNavigationBarVC的页面 也没有显示自定义导航。是不支持模态的形式嘛

**Comment by SmileZXLee** [comment]
> push出来的B页面没有相关代码，是其他问题导致的没有隐藏系统导航。
> 补充提问：模态present推一个继承ZXNavigationBarVC的页面 也没有显示自定义导航。是不支持模态的形式嘛

* 您好，您可以看下其他第三方的分类或者继承的根控制器，是否有展示导航栏的操作，或者在您的根控制器页面加载时，调用一下隐藏系统导航栏的方法，若方便的话可以提供给我一个demo我这边寻找一下原因。
* present推一个继承ZXNavigationBarVC的页面是不会展示导航栏的，需要创建一个导航控制器，并设置这个导航控制器的根控制器为您要present的这个控制器，同时present这个导航控制器，`ZXNavigationBar`控制导航栏是否显示的逻辑与系统导航栏是保持一致的。

**Comment by WangJxin1992** [comment]
好的 谢谢。
