### ISSUE TITLE
关于iPhone 12 mini NavigationBar 总高度问题

### ISSUE THREAD

**Issue by jianjianhao** [SmileZXLee/ZXNavigationBar#25]
目前使用的是xcode12.2  iPhone 12 mini 模拟器出现的情况
按照以往常规的计算就是用状态栏高度加上NavigationBar固定44的高度来获取上面总的高度
示例代码 
STATUSBAR_HEIGHT = [UIApplication sharedApplication].statusBarFrame.size.height 
NAVBAR_HEIGHT  = 44.0f
STATUSBAR_NAVBAR_HEIGHT = STATUSBAR_HEIGHT + NAVBAR_HEIGHT;
经过测试除了iPhone 12 mini 模拟器的高度有问题，其他的设备正常
目前iPhone 12 mini通过代码计算获取是88的高度，但是我随便新建一个项目工程打印总高度是94，也不知道是不是模拟器bug，因为没有真机暂时无法定位具体问题
这里提供截图和打印信息
<img width="667" alt="CC552D75-4277-4B44-812A-4D472B8E5AD1" src="https://user-images.githubusercontent.com/12797357/100033787-cc42b400-2e35-11eb-9100-da7780f5f232.png">

**Comment by SmileZXLee** [comment]
嗯嗯，经过测试，12mini下通过代码获取到的状态栏高度是44，导航栏固定的高度为44，正常应该是88才对。通过打印，系统导航栏y值为50，状态栏高度为44，状态栏与导航栏中间间隔了6像素不知道哪里来的。
如果全局都使用的是自定义导航栏，对整个项目是没有影响的，因为自定义导航栏实际上为控制器view，因此可以忽视系统导航栏的高度了。

**Comment by jianjianhao** [comment]
哎旧项目就有点尴尬了，想换成大佬的框架就是，改动的比较大难受

**Comment by SmileZXLee** [comment]
如果旧项目要换成`ZXNavigationBar`的话，`self.title=@"xxx"`这个是不需要调整的，其他例如设置导航栏item这些需要手动更改，会比较麻烦一些。
12mini因为没有真机，不大确定是否是模拟器的bug，不过我看了模拟器上的94很丑，看着有点难受，因为mini本身比较小，导航栏反而更高，看起来不协调，所以觉得还是原来的88更好些。
我不是大佬，只是普通的程序员，有任何问题可以互相探讨交流哈，如果有需要调整的地方，我会第一时间解决的！感谢使用和认可(*╹▽╹*)

**Comment by jianjianhao** [comment]
作者我刚刚试了下在iPhone 12 mini 切换系统导航栏的时候侧滑返回，demo的视图会往下面掉下去
<img width="433" alt="57AF44C3-E9EE-4C6E-9106-961B959A7298" src="https://user-images.githubusercontent.com/12797357/100067450-42b0d780-2e71-11eb-88ef-9bcd5d9603b0.png">
估计这种比较难搞，哎系统的玩意真坑

**Comment by jianjianhao** [comment]
其系统的也就会喔，估计是要处理

**Comment by SmileZXLee** [comment]
> 作者我刚刚试了下在iPhone 12 mini 切换系统导航栏的时候侧滑返回，demo的视图会往下面掉下去
> <img alt="57AF44C3-E9EE-4C6E-9106-961B959A7298" width="433" src="https://user-images.githubusercontent.com/12797357/100067450-42b0d780-2e71-11eb-88ef-9bcd5d9603b0.png">
> 估计这种比较难搞，哎系统的玩意真坑

感谢提醒！此问题已修复，可以更新到1.3.0哦

**Comment by Soldoros** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/11658793/137688102-2a2da04e-681b-49e3-be08-62a35471ea29.png">
