### ISSUE TITLE
有没有白名单功能

### ISSUE THREAD

**Issue by jianjianhao** [SmileZXLee/ZXNavigationBar#26]
想加白名单直接过滤掉不用的vc，要是能做到直接前缀就更好，旧项目用到了云信的uikit的框架，里面有不少vc又不想改源码，作者大大有没有简单的方法

**Comment by jianjianhao** [comment]
方便的话加下QQ或者wx联系也行

**Comment by SmileZXLee** [comment]
> 方便的话加下QQ或者wx联系也行

加一下我wx哦，我们讨论一下细节：a393727164~
