### ISSUE TITLE
在controller上布局的view上移了导航栏加状态栏高度，没有使用XIB

### ISSUE THREAD

**Issue by SunBoyXiao** [SmileZXLee/ZXNavigationBar#28]
在controller上使用Masonry布局的view上移了导航栏加状态栏高度，没有使用XIB。请问改怎么设置。如果在界面上隐藏ZXNavigationBar是正常。反之就不正常。

**Comment by SmileZXLee** [comment]
你好，如果您使用的Masonry布局，可以进行如下设置：
假设testView需要铺满整个屏幕，并且不被导航栏遮挡
***
设置testView的top和self.zx_navLineView(导航栏分割线)相同
```objc
[testView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.equalTo(self.view);
    make.top.equalTo(self.zx_navLineView);
    make.right.equalTo(self.view));
    make.bottom.equalTo(self.view);
}];
```
或设置testView的top和self.view的top距离为导航栏高度(导航栏高度使用`ZXNavBarHeight`这个宏获取)
```objc
[testView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.equalTo(self.view);
    make.top.equalTo(self.view).with.offset(ZXNavBarHeight);
    make.right.equalTo(self.view);
    make.bottom.equalTo(self.view);
}];
```

**Comment by SunBoyXiao** [comment]
> 你好，如果您使用的Masonry布局，可以进行如下设置：
> 假设testView需要铺满整个屏幕，并且不被导航栏遮挡
> 
> 设置testView的top和self.zx_navLineView(导航栏分割线)相同
> 
> ```objc
> [testView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.left.equalTo(self.view);
>     make.top.equalTo(self.zx_navLineView);
>     make.right.equalTo(self.view));
>     make.bottom.equalTo(self.view);
> }];
> ```
> 
> 或设置testView的top和self.view的top距离为导航栏高度(导航栏高度使用`ZXNavBarHeight`这个宏获取)
> 
> ```objc
> [testView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.left.equalTo(self.view);
>     make.top.equalTo(self.view).with.offset(ZXNavBarHeight);
>     make.right.equalTo(self.view);
>     make.bottom.equalTo(self.view);
> }];
> ```

谢谢您的答复，我使用的是第二种方法。

**Comment by SmileZXLee** [comment]
> > 你好，如果您使用的Masonry布局，可以进行如下设置：
> 
> > 假设testView需要铺满整个屏幕，并且不被导航栏遮挡
> 
> > 
> 
> > 设置testView的top和self.zx_navLineView(导航栏分割线)相同
> 
> > 
> 
> > ```objc
> 
> > [testView mas_makeConstraints:^(MASConstraintMaker *make) {
> 
> >     make.left.equalTo(self.view);
> 
> >     make.top.equalTo(self.zx_navLineView);
> 
> >     make.right.equalTo(self.view));
> 
> >     make.bottom.equalTo(self.view);
> 
> > }];
> 
> > ```
> 
> > 
> 
> > 或设置testView的top和self.view的top距离为导航栏高度(导航栏高度使用`ZXNavBarHeight`这个宏获取)
> 
> > 
> 
> > ```objc
> 
> > [testView mas_makeConstraints:^(MASConstraintMaker *make) {
> 
> >     make.left.equalTo(self.view);
> 
> >     make.top.equalTo(self.view).with.offset(ZXNavBarHeight);
> 
> >     make.right.equalTo(self.view);
> 
> >     make.bottom.equalTo(self.view);
> 
> > }];
> 
> > ```
> 
> 
> 
> 谢谢您的答复，我使用的是第二种方法。

使用后是否达到预期的效果。

**Comment by SunBoyXiao** [comment]
完全可以达到效果。目前遇到一个新的问题，子控制器是UICollectionView，UICollectionView有headerView，headerView上面嵌套一个UICollectionView，当滑动headerView上面的UICollectionView时会冲突，是需要使用WMZBannerView吗？但是我的不是轮播图。

**Comment by SmileZXLee** [comment]
> 完全可以达到效果。目前遇到一个新的问题，子控制器是UICollectionView，UICollectionView有headerView，headerView上面嵌套一个UICollectionView，当滑动headerView上面的UICollectionView时会冲突，是需要使用WMZBannerView吗？但是我的不是轮播图。

可以提供截图、录屏、demo或详细的描述吗，我在项目中使用tableView的headerView嵌套`SDCycleScrollView`使用是正常的。`SDCycleScrollView`是使用UICollectionView实现的。

**Comment by SunBoyXiao** [comment]
> > 完全可以达到效果。目前遇到一个新的问题，子控制器是UICollectionView，UICollectionView有headerView，headerView上面嵌套一个UICollectionView，当滑动headerView上面的UICollectionView时会冲突，是需要使用WMZBannerView吗？但是我的不是轮播图。
> 
> 可以提供截图、录屏、demo或详细的描述吗，我在项目中使用tableView的headerView嵌套`SDCycleScrollView`使用是正常的。`SDCycleScrollView`是使用UICollectionView实现的。

问题已经解决了，是我代码的问题。

**Comment by SmileZXLee** [comment]
好的
