### ISSUE TITLE
push到B页面，B页面有个分页控制器，在分页控制器里面的第一页里面不能响应全屏返回手势

### ISSUE THREAD

**Issue by SunBoyXiao** [SmileZXLee/ZXNavigationBar#29]
//加这一行代码即可解决ScrollView与侧滑返回手势冲突问题
    //[self zx_setPopGestureCompatibleScrollView:self.pageController.downSc];
    __weak typeof(self) weakSelf = self;
    self.zx_popGestureShouldRecognizeSimultaneously = ^BOOL(UIGestureRecognizer * _Nonnull otherGestureRecognizer) {
        if(weakSelf.pageController.downSc.contentOffset.x <= 0){
            return YES;
        }
        return NO;
    };
这个代码加了没效果。

**Comment by SunBoyXiao** [comment]
> //加这一行代码即可解决ScrollView与侧滑返回手势冲突问题
> //[self zx_setPopGestureCompatibleScrollView:self.pageController.downSc];
> __weak typeof(self) weakSelf = self;
> self.zx_popGestureShouldRecognizeSimultaneously = ^BOOL(UIGestureRecognizer * _Nonnull otherGestureRecognizer) {
> if(weakSelf.pageController.downSc.contentOffset.x <= 0){
> return YES;
> }
> return NO;
> };
> 这个代码加了没效果。

**Comment by SmileZXLee** [comment]
这个问题是否已解决了
