### ISSUE TITLE
UIViewController 继承ZXNavigationBarController后, 使用三方库PYSearch有问题

### ISSUE THREAD

**Issue by Levofloxacin** [SmileZXLee/ZXNavigationBar#30]
如题..
继承UIViewController 的时候没问题..
继承ZXNavigationBarController后, PYSearch页面是空白的..
PYSearch可以在github上搜索

**Comment by SmileZXLee** [comment]
PYSearch使用的是系统导航栏，因此自定义导航栏时无法显示导航栏顶部的搜索框。以下是解决方案：
* 设置`PYSearchViewController`继承于`ZXNavigationBarController`。
* 在push `PYSearchViewController `时，设置
```objc
//searchViewController为PYSearchViewController对象
searchViewController.zx_showSystemNavBar = YES;
self.zx_navEnableSmoothFromSystemNavBar = YES;
```
* 如果需要系统导航栏与自定义导航栏更平滑的过渡效果，可将导航控制器继承于`ZXNavigationBarNavigationController`。
***
您也可以在不修改`PYSearchViewController`源码的情况下达到此效果
* 在push `PYSearchViewController `时，设置（但过渡效果不好，如果使用modal展示，则可以忽视过渡问题）
```objc
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(CGFLOAT_MIN * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    self.navigationController.navigationBarHidden = NO;
});
```
附demo：
[PYSearch-master.zip](https://github.com/SmileZXLee/ZXNavigationBar/files/5686313/PYSearch-master.zip)

**Comment by Levofloxacin** [comment]
抱歉,这么久才回复.
总之感谢作者...
导航很好用.. 避免了肯多坑.谢谢..

**Comment by SmileZXLee** [comment]
不客气，很高兴可以帮到你，有任何问题可以随时反馈哦。
