### ISSUE TITLE
关于tableViewController

### ISSUE THREAD

**Issue by lcf15980849273** [SmileZXLee/ZXNavigationBar#32]
如何支持tableViewController呢? 一些页面想在storyBoard上直接用TableViewController的静态cell画UI，没办法继承作者的ZXNavigationBarController，能否扩展一下？

**Comment by SmileZXLee** [comment]
因为需要继承`ZXNavigationBarController`才能实现相关功能，而`UITableViewController`继承于`UIViewController`并且无法修改这一继承关系，所以只能将`ZXNavigationBarController`中的所有属性和方法变成分类才可以实现，但是这样处理的话，对整体结构破坏很大，因此建议您在storyBoard创建一个普通`UIViewController`并且拖一个tableView并设置约束，可以达到同等的目的。

**Comment by lcf15980849273** [comment]
你好，感觉可以弄一个ZXNavigationBarTableViewController，功能和ZXNavigationBarController类似，只是一些地方稍加修改，比如自定义的navigationBar的悬停问题等。因为在storyBoard创建一个普通UIViewController并且拖一个tableView并设置约束，不能设置tableView为静态cell，不知道是不是我不懂

**Comment by SmileZXLee** [comment]
感谢您的建议，1.3.8版本已添加继承于UITableViewController的ZXNavigationBarTableViewController。
