### ISSUE TITLE
设置多个ScrollView手势冲突,只有最后一个才会支持手势返回

### ISSUE THREAD

**Issue by Levofloxacin** [SmileZXLee/ZXNavigationBar#33]
如果一个ViewController里, 有一个横向移动的UICollectionView, 还有一个UIScrollview分页控制器的话.
如下设置,
[self zx_setPopGestureCompatibleScrollView:self.horizontalView.collectionView];
[self zx_setPopGestureCompatibleScrollView:self.scrollView];
或者
[self zx_setPopGestureCompatibleScrollViews:@[self.horizontalView.collectionView, self.scrollView]];

这样设置的话, 只有最后一个设置手势冲突的UIView,才会支持手势返回.

**Comment by SmileZXLee** [comment]
感谢反馈，1.3.8版本已修复这一问题

**Comment by Levofloxacin** [comment]
谢谢
