### ISSUE TITLE
如果将ZXNavigationBar的导航栏隐藏了是不是就不能监听返回手势了

### ISSUE THREAD

**Issue by SunBoyXiao** [SmileZXLee/ZXNavigationBar#34]
在控制器里面加了self.zx_hideBaseNavBar = YES;
那么下面的拦截侧滑返回的手势就失效了吗？
//拦截侧滑返回手势和返回按钮点击事件
    self.zx_handlePopBlock = ^BOOL(ZXNavigationBarController * _Nonnull viewController, ZXNavPopBlockFrom popBlockFrom) {
        //viewController:当前控制器
        //popBlockFrom:通过什么方式(点击返回按钮或侧滑返回手势)触发pop操作
        
        //doSomething
        //返回YES则代表不禁止pop操作，返回NO则禁止pop操作
        @strongify(self);
        [self backClick];
        
        return NO;
    };

**Comment by SmileZXLee** [comment]
加了`self.zx_hideBaseNavBar = YES;`以后 `self.zx_handlePopBlock`不会失效。
如您发现`self.zx_handlePopBlock`无效，请将您的版本更新到最新：1.3.8后再次尝试。

**Comment by SunBoyXiao** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/6668186/103856925-7168d180-50f0-11eb-975e-67f71f84f127.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6668186/103857001-9a896200-50f0-11eb-97ba-4b3bfcb01e29.png">
已更新到最新版本
第一张图，设置了侧滑返回手势的范围为0.2，但是还是可以全屏侧滑返回；
第二张图，子控制器中监听侧滑返回手势没作用，不会走。

**Comment by SmileZXLee** [comment]
我按照您的设置测试了一遍，`zx_popGestureCoverRatio`和`zx_handlePopBlock`都可以正常工作，您可以下载一下此项目的demo，并修改demo中任一控制器的配置，看下是否是正常的哈，如果可以复现可以把测试项目压缩一下发给我，感谢！

**Comment by SunBoyXiao** [comment]
大佬，是否有QQ交流群或者联系方式？

**Comment by SmileZXLee** [comment]
> 大佬，是否有QQ交流群或者联系方式？

qq群[790460711](https://jq.qq.com/?_wv=1027&k=vU2fKZZH)可以加群交流一下哈
