### ISSUE TITLE
iOS 14.0.1  popToRoot 时tabbar消失 

### ISSUE THREAD

**Issue by H4AER** [SmileZXLee/ZXNavigationBar#35]
这个可以处理一下吗 navi和vc继承本库

**Comment by H4AER** [comment]
https://user-images.githubusercontent.com/15047422/104151300-9f635400-5417-11eb-8b3d-32da763a1451.mp4

**Comment by H4AER** [comment]
https://gitee.com/1264788359/pro/raw/master/QQ20210111-141400-HD.mp4

**Comment by SmileZXLee** [comment]
navi和vc 继承系统的导航控制器和普通控制器，是否依然会出现此问题。

**Comment by H4AER** [comment]
不会，应该是这个问题https://www.jianshu.com/p/30ffeee213fe
目前在14.0的真机上有这一问题

---原始邮件---
发件人: "ZXLee"<notifications@github.com&gt;
发送时间: 2021年1月12日(周二) 晚上10:22
收件人: "SmileZXLee/ZXNavigationBar"<ZXNavigationBar@noreply.github.com&gt;;
抄送: "liu"<1264788359@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [SmileZXLee/ZXNavigationBar] iOS 14.0.1  popToRoot 时tabbar消失  (#35)




 
navi和vc 继承系统的导航控制器和普通控制器，是否依然会出现此问题。

**Comment by SmileZXLee** [comment]
感谢您提供的解决方案。
因为我目前没有iOS 14.0的真机，劳烦您帮我测试一下：
* 修改`ZXNavigationBarNavigationController.m`的`-popToRootViewControllerAnimated`方法（第48行）：
```objc
- (NSArray<UIViewController *> *)popToRootViewControllerAnimated:(BOOL)animated{
    if(self.viewControllers.firstObject && !self.doingPopGesture){
        [self updateTopViewController:self.viewControllers.firstObject];
    }
    if(!self.zx_disableAutoHidesBottomBarWhenPushed && self.viewControllers.count > 1){
        self.topViewController.hidesBottomBarWhenPushed = NO;
    }
    return [super popToRootViewControllerAnimated:animated];
}
```
然后测试一下问题是否已解决哈，谢谢！

**Comment by H4AER** [comment]
可以的
