### ISSUE TITLE
我想在当前页面禁止pop手势,或者是拦截返回手势,设置以下无效,

### ISSUE THREAD

**Issue by Levofloxacin** [SmileZXLee/ZXNavigationBar#37]
请问具体需要怎么操作.谢谢.

- (void)viewWillAppear:(BOOL)animated {
    self.zx_popGestureCoverRatio = 0.1;
    self.zx_handlePopBlock = ^BOOL(ZXNavigationBarController * _Nonnull viewController, ZXNavPopBlockFrom popBlockFrom) {
        //viewController:当前控制器
        //popBlockFrom:通过什么方式(点击返回按钮或侧滑返回手势)触发pop操作

        //doSomething
        //返回YES则代表不禁止pop操作，返回NO则禁止pop操作
        NSLog(@"");
        return NO;
    };
}

**Comment by SmileZXLee** [comment]
1.是否在项目中同时使用了`FDFullscreenPopGesture`，若使用了可以参照readme中关于兼容`FDFullscreenPopGesture`的相关处理或者直接移除`FDFullscreenPopGesture`。
2.是否是最新版本的（1.3.9）若不是最新版本，可以更新一下。
3.如果问题仍未解决，可以随时回复，或者加入qq群[790460711](https://jq.qq.com/?_wv=1027&k=vU2fKZZH)交流~

**Comment by Levofloxacin** [comment]
抱歉是我的问题..
提问题之前, 我看到了FDFull相关的问题.. 我以为我的项目没有FD 后来找了一圈发现了FD..
移除掉FD后, 功能正常
