### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by W-hale** [SmileZXLee/ZXNavigationBar#38]
#pragma mark - 重写父类pop和push相关方法
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated{
    self.navigationBarHidden = YES;
    [self updateTopViewController:viewController];
    if(!self.zx_disableAutoHidesBottomBarWhenPushed){
        [viewController setHidesBottomBarWhenPushed:self.viewControllers.count  >= 1];
    }
    [super pushViewController:viewController animated:YES];
}

改为

[super pushViewController:viewController animated:animated];

项目中用到，有时候真的不需要动画....

**Comment by SmileZXLee** [comment]
这个地方是我的失误所致，感谢提醒，这个问题将在下个版本修复。
