### ISSUE TITLE
BackButtonHandlerProtocol 协议名重复

### ISSUE THREAD

**Issue by zhangzhihua2019** [SmileZXLee/ZXNavigationBar#39]
BackButtonHandlerProtocol 这个协议,和老项目里有uiviewcontroller的分类的协议名字一样,导致项目报错无法运行,我可以给老项目的协议名更改吗? 改了会有影响吗?   你这在pod 没法改,加个前缀.

**Comment by SmileZXLee** [comment]
感谢反馈，在下一版本中`BackButtonHandlerProtocol `协议将添加前缀。目前您可以修改这个协议名字即可解决报错，修改协议名字对项目没有影响。
