### ISSUE TITLE
当导航条透明时跳转到使用系统导航条的页面，返回的时候顶部透明效果需要优化

### ISSUE THREAD

**Issue by myDonghao** [SmileZXLee/ZXNavigationBar#4]
hello，大佬，我又来了！来一波py交易
需要优化的样式：
![IMG_889A59961173-1](https://user-images.githubusercontent.com/20014338/83093258-a714f900-a0d1-11ea-9ba7-8e277283ef76.jpeg)
复现方法：
在微博demo`DemoWeiboHotViewController`中 设置右上角按钮点击跳转到使用系统导航条的页面
```objc
    [self zx_setRightBtnWithImgName:@"right_more_icon" clickedBlock:^(ZXNavItemBtn * _Nonnull btn) {
        NSLog(@"点击了最右边的按钮");
        Class DemoSystemBarViewController = NSClassFromString(@"DemoSystemBarViewController");
        id vc = [DemoSystemBarViewController new];
        [self.navigationController pushViewController:vc animated:YES];
    }];

```
看看能不能优化一波。

**Comment by SmileZXLee** [comment]
> hello，大佬，我又来了！来一波py交易
> 需要优化的样式：
> ![IMG_889A59961173-1](https://user-images.githubusercontent.com/20014338/83093258-a714f900-a0d1-11ea-9ba7-8e277283ef76.jpeg)
> 复现方法：
> 在微博demo`DemoWeiboHotViewController`中 设置右上角按钮点击跳转到使用系统导航条的页面
> 
> ```objc
>     [self zx_setRightBtnWithImgName:@"right_more_icon" clickedBlock:^(ZXNavItemBtn * _Nonnull btn) {
>         NSLog(@"点击了最右边的按钮");
>         Class DemoSystemBarViewController = NSClassFromString(@"DemoSystemBarViewController");
>         id vc = [DemoSystemBarViewController new];
>         [self.navigationController pushViewController:vc animated:YES];
>     }];
> ```
> 
> 看看能不能优化一波。

感谢您的建议，最新版本已优化，可以下载Demo查看哦~~
