### ISSUE TITLE
设置状态栏颜色不管事怎么解决

### ISSUE THREAD

**Issue by ke112** [SmileZXLee/ZXNavigationBar#40]
self.zx_navStatusBarStyle = ZXNavStatusBarStyleLight;    在当前控制器,不管事,怎么解决???

-(UIStatusBarStyle)preferredStatusBarStyle{
    return UIStatusBarStyleLightContent;
}
下边这种方法也不管事,还是黑色的,不知道为什么?

**Comment by SmileZXLee** [comment]
方便提供一下demo吗，可以帮助我排查问题，谢谢。

**Comment by SmileZXLee** [comment]
我在测试项目中测试是正常的，可能受其他因素影响，比如preferredStatusBarStyle被覆盖等，提供demo可以帮助我快速定位和处理此问题。

**Comment by zhangzhihua2019** [comment]
demo 不太方便提供,是公司项目里的,关键代码 在我的界面   老代码 用到了
[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault];

我从我的界面跳转新写的界面,,,继承你的父类controller,
self.zx_navStatusBarStyle = ZXNavStatusBarStyleLight; 在当前控制器,不管事,怎么解决???

-(UIStatusBarStyle)preferredStatusBarStyle{
return UIStatusBarStyleLightContent;
}
这两个方法 都不管事,请问这是怎么回事?

**Comment by zhangzhihua2019** [comment]
我的个人中心界面 老代码是这样的 : 

- (void)viewWillDisappear:(BOOL)animated{
    [super viewWillDisappear:animated];
    [self.navigationController setNavigationBarHidden:NO animated:animated];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault];
}

然后跳转的子模块的继承你的 ZXNavigationBarController 控制器,调用以上方法无效

**Comment by SmileZXLee** [comment]
我按照您上面描述进行设置，未发现异常，您可以下载一下这个项目的demo，在这个项目基础上改来复现这个问题哈，感谢。

**Comment by zhangzhihua2019** [comment]
我发现原因了,因为我项目View controller-based status bar appearance 设置的是NO,用你设置状态栏的方法 所以不管事,用你的框架,项目的这个属性,必须设置YES吗

**Comment by SmileZXLee** [comment]
感谢反馈，新版本已修复设置了View controller-based status bar appearance为NO时无法控制状态栏颜色的问题，请更新至1.4.0。

**Comment by Vent-Frais** [comment]
可以，我也碰到了同样的问题。用其他方式解决了。现在这样方便多了

**Comment by zhangzhihua2019** [comment]
感谢,我稍后用新的版本试一下.
