### ISSUE TITLE
TableViewController的显示有问题。

### ISSUE THREAD

**Issue by Vent-Frais** [SmileZXLee/ZXNavigationBar#41]
我看到你有设置ZXNavigationBarTableViewController，继承了之后，tableview的表头会计算成没有导航栏，会在 ZXNavigationBar的下面。

**Comment by XuDongLiu-star** [comment]
尤其是设置了TableHeaderView后

**Comment by SmileZXLee** [comment]
感谢反馈，此问题已修复，请更新至1.4.0。
