### ISSUE TITLE
请问侧滑返回能增加像系统导航那种渐变吗

### ISSUE THREAD

**Issue by tfy87happy** [SmileZXLee/ZXNavigationBar#42]
请问侧滑返回能增加像系统导航那种渐变吗？现在侧滑效果有点硬邦邦的

**Comment by SmileZXLee** [comment]
因为使用的是自定义导航栏，导航栏是属于控制器的子view，不是导航控制器的view，因此无法增加类似系统导航栏的渐变哈。
