### ISSUE TITLE
TableViewController还是有比较严重的问题

### ISSUE THREAD

**Issue by Vent-Frais** [SmileZXLee/ZXNavigationBar#43]
基本情况：静态表格，设置个tableHeaderView,在单元格中放置一个或几个textView。当textView输入文字产生换行时，顶部导航栏高度计算就会出问题，会延伸覆盖tableHeaderView。是在storyboard中设置的。应该区别不大。

**Comment by Vent-Frais** [comment]
问题已解决，视图中包含多个scrollview会引起冲突，已提交pull request

#pragma mark scrollView滚动，请勿重写此方法，否则导航栏将跟着scrollView一起移动
- (void)scrollViewDidScroll:(UIScrollView *)scrollView{
    self.didDoScroll = YES;
    if (scrollView == self.tableView) {
        self.zx_navBar.zx_y =  scrollView.contentOffset.y;
    }
    [self zx_scrollViewDidScroll:scrollView];
}

**Comment by SmileZXLee** [comment]
收到，感谢您的帮助！
