### ISSUE TITLE
zx_setPopGestureCompatibleScrollView返回手势冲突解决问题

### ISSUE THREAD

**Issue by Wuou** [SmileZXLee/ZXNavigationBar#47]
如果VC设置了zx_setPopGestureCompatibleScrollView后，而该VC是添加到UITabBarController的，会导致所有点击失效，APP就卡住了
![simulator_screenshot_2D186F9D-3538-45B4-8B5E-05085F862D3A](https://user-images.githubusercontent.com/14285500/120622770-b15e9580-c491-11eb-942e-cdad29819c46.png)

**Comment by SmileZXLee** [comment]
### 您好，我在demo中测试未发现此问题。请尝试将`ZXNavigationBar`更新到最新版本。  
### 测试demo地址：[http://zxlee.oss-cn-shanghai.aliyuncs.com/temp/ZXNavigationBarTestDemo2.zip](http://zxlee.oss-cn-shanghai.aliyuncs.com/temp/ZXNavigationBarTestDemo2.zip)，可以下载试一下。  
### 若问题依旧，请提供可复现的demo以便我排查，感谢！！

**Comment by Wuou** [comment]
> ### 您好，我在demo中测试未发现此问题。请尝试将`ZXNavigationBar`更新到最新版本。
> ### 测试demo地址：http://zxlee.oss-cn-shanghai.aliyuncs.com/temp/ZXNavigationBarTestDemo2.zip，可以下载试一下。
> ### 若问题依旧，请提供可复现的demo以便我排查，感谢！！
有可能是侧滑框架的问题，我在看下吧

**Comment by SmileZXLee** [comment]
#### 【重要】如果您在项目中使用了`FDFullscreenPopGesture`
* `ZXNavigationBar`支持全屏手势返回和拦截，建议您移除其他的第三方全屏手势返回框架以避免冲突。
* 若自定义导航栏与系统导航栏同在一个项目中，您可以在继承于`ZXNavigationBarController`的跟控制器的初始化方法书写以下代码以兼容`FDFullscreenPopGesture`:
```objective-c
//因FDFullscreenPopGesture默认会在控制器即将展示时显示系统导航栏，与ZXNavigationBar共同使用时会造成系统导航栏出现一下又马上消失，因此需要以下设置
self.fd_prefersNavigationBarHidden = YES;
//当您通过zx_handlePopBlock拦截侧滑返回手势时，请设置fd_interactivePopDisabled为YES以关闭FDFullscreenPopGesture在当前控制器的全屏返回手势，否则无法拦截。
self.fd_interactivePopDisabled = YES;
```
