### ISSUE TITLE
如果viewcontroller里面并排两个tableview，第二个tableview就会到导航栏下面去了

### ISSUE THREAD

**Issue by Vent-Frais** [SmileZXLee/ZXNavigationBar#48]
在sb中设置两个tableview顶部到导航栏下方，貌似只计算了第一个tableview的安全距离。你这个有多个滚动容器的时候容易出问题。

**Comment by SmileZXLee** [comment]
有两种解决方式。  
1.设置`self.zx_enableAdjustNavContainerAll = YES;`【xib加载控制器情况下将所有约束为top且secondItem为控制器view或safeArea的子view约束constant设置为原始长度+导航栏高度，默认为NO(仅第一个)，若设置为YES，将会遍历控制器view中的所有约束，对性能有一点影响（需要设置在[super viewDidLoad]之前）】  
2.用一个view包住所有的view，也就是控制器view中只有一个子view，子view中包含了其他view。
