### ISSUE TITLE
好像对TableViewController失效了

### ISSUE THREAD

**Issue by meliuxudong** [SmileZXLee/ZXNavigationBar#51]
我新建项目用ZXNavigationBarTableViewController 设置TableViewController无效了。上方导航栏是空白的。普通的ViewController是正常的，而且我打开之前的项目，是正常的。新建项目的代码和用法完全复制之前项目的，只是xcode升级了，不知道你这个版本的代码测试过没有

**Comment by meliuxudong** [comment]
其他正常，应该是设置背景图片失效了。

**Comment by meliuxudong** [comment]
费我半天劲，终于找到bug在哪里了。应该是self.zx_bacImageView.frame = self.bounds; 你写的是self.frame

**Comment by SmileZXLee** [comment]
收到，感谢反馈~
