### ISSUE TITLE
合qq的QMUIKit共同使用出现一个bug

### ISSUE THREAD

**Issue by myDonghao** [SmileZXLee/ZXNavigationBar#9]
我也不清楚是什么原因！就是我使用`ZXNavigationBarNavigationController`作为导航控制器的时候，侧滑的时候可以复现。
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/20014338/87662799-5c406500-c795-11ea-9c1e-9d06100ee004.png">
在这个地方开始多次循环然后野指针了。
QMUIKit里面的`UIView+QMUI`这个分类里面
<img width="893" alt="image" src="https://user-images.githubusercontent.com/20014338/87662936-9ad61f80-c795-11ea-9095-c3dac48f8fb3.png">
我搞不清楚是什么问题了，大佬能不能帮忙看一下。
DEMO中pod导入 `pod 'QMUIKit'`，侧滑即可复现。

**Comment by SmileZXLee** [comment]
感谢反馈，由于QMUIKit在UINavigationController+QMUI.m中，将所有导航控制器的self.interactivePopGestureRecognizer.delegate设置为导航控制器本身，导致handleNavigationTransition方法无限递归，我在新版本中已经修复了这个问题，您可以更新一下1.1.8版本即可兼容QMUIKit。

**Comment by SmileZXLee** [comment]
感谢反馈，由于QMUIKit在UINavigationController+QMUI.m中将self.interactivePopGestureRecognizer.delegate设置为导航控制器本身，ZXNavigationBarNavigationController未妥善处理这种情况导致代理为自身时`handleNavigationTransition:`方法无限递归调用，我在1.1.8版本中修复了这个问题，您可以更新一下即可兼容QMUIKit。

> 我也不清楚是什么原因！就是我使用`ZXNavigationBarNavigationController`作为导航控制器的时候，侧滑的时候可以复现。
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/20014338/87662799-5c406500-c795-11ea-9c1e-9d06100ee004.png">
> 在这个地方开始多次循环然后野指针了。
> QMUIKit里面的`UIView+QMUI`这个分类里面
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/20014338/87662936-9ad61f80-c795-11ea-9095-c3dac48f8fb3.png">
> 我搞不清楚是什么问题了，大佬能不能帮忙看一下。
> DEMO中pod导入 `pod 'QMUIKit'`，侧滑即可复现。



> 我也不清楚是什么原因！就是我使用`ZXNavigationBarNavigationController`作为导航控制器的时候，侧滑的时候可以复现。
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/20014338/87662799-5c406500-c795-11ea-9c1e-9d06100ee004.png">
> 在这个地方开始多次循环然后野指针了。
> QMUIKit里面的`UIView+QMUI`这个分类里面
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/20014338/87662936-9ad61f80-c795-11ea-9095-c3dac48f8fb3.png">
> 我搞不清楚是什么问题了，大佬能不能帮忙看一下。
> DEMO中pod导入 `pod 'QMUIKit'`，侧滑即可复现。

感谢反馈，由于QMUIKit在UINavigationController+QMUI.m中将self.interactivePopGestureRecognizer.delegate设置为导航控制器本身，ZXNavigationBarNavigationController未妥善处理这种情况导致代理为自身时`handleNavigationTransition:`方法无限递归调用，我在1.1.8版本中修复了这个问题，您可以更新一下即可兼容QMUIKit。

**Comment by SmileZXLee** [comment]
感谢反馈，由于QMUIKit在UINavigationController+QMUI.m中将self.interactivePopGestureRecognizer.delegate设置为导航控制器本身，ZXNavigationBarNavigationController未妥善处理这种情况导致代理为自身时`handleNavigationTransition:`方法无限递归调用，我在1.1.8版本中修复了这个问题，您可以更新一下即可兼容QMUIKit。

**Comment by myDonghao** [comment]
好的，谢谢大佬，嘿嘿，QMUIIkit他那个c语言风格的代码我看的头都大了

**Comment by SmileZXLee** [comment]
> 好的，谢谢大佬，嘿嘿，QMUIIkit他那个c语言风格的代码我看的头都大了

不客气，很高兴能帮到你。
